### PR TITLE
Fix the binders topology layer

### PR DESCRIPTION
**Pull request by ronawho**
Add a missing qt_alloc include to the binders topology layer. Also adds
CI testing for binders.

### CODE REVIEW

**Comment by ronawho** [comment]
Opening as a draft and will rebase/un-draft after https://github.com/Qthreads/qthreads/pull/81

**Comment by janciesko** [comment]
I'll cherry-pick 01dcea3 and f92810b from this PR.

**Comment by janciesko** [comment]
Ok, great!

**Comment by ronawho** [comment]
Rebased and un-drafted (github actions CI tests are running now too)

**Review by janciesko — APPROVED** [review]

**Pull request merged**
