### PR TITLE
Add package gen automation script

### PR DESCRIPTION
**Pull request by janciesko**

### CODE REVIEW

**Review by olivier-snl — COMMENTED** [review]
LGTM.  You could crossreference the files deleted with the older releases if you wanted to check if you missed any (if you haven't done so already).

**Comment by janciesko** [comment]
```diff -qr qthreads-1.18 qthread-1.17 | grep "Only in"```
```
Only in qthread-1.17/config: compile
Only in qthread-1.17/config: config.guess
Only in qthread-1.17/config: config.sub
Only in qthread-1.17/config: depcomp
Only in qthread-1.17/config: install-sh
Only in qthread-1.17/config: libtool.m4
Only in qthread-1.17/config: ltmain.sh
Only in qthread-1.17/config: lt~obsolete.m4
Only in qthread-1.17/config: ltoptions.m4
Only in qthread-1.17/config: ltsugar.m4
Only in qthread-1.17/config: ltversion.m4
Only in qthread-1.17/config: missing
Only in qthread-1.17/config: test-driver
Only in qthreads-1.18: .dir-locals.el
Only in qthreads-1.18: .git
Only in qthreads-1.18: .github
Only in qthreads-1.18: .gitignore
Only in qthreads-1.18: .gitlab-ci.yml
Only in qthread-1.17/include/qthread: stamp-h2
Only in qthreads-1.18/scripts: package.sh
Only in qthreads-1.18/test/perf: Makefile
Only in qthreads-1.18/test/stress: lock_acq_rel.c
Only in qthreads-1.18: .travis.yml
```

I'll issue a PR to remove the stray Makefile:
```
"Only in qthreads-1.18/test/perf: Makefile" 
```

**Comment by janciesko** [comment]
The script deletes too many filed. Updating the script.

**Comment by janciesko** [comment]
Update: 

```
diff -qr qthreads-1.18 qthread-1.17 | grep "Only in"
```
```
Only in qthread-1.17: .autogen-version
Only in qthread-1.17/include/qthread: stamp-h2
Only in qthreads-1.18/scripts: package.sh
Only in qthreads-1.18/test/perf: Makefile
Only in qthreads-1.18/test/stress: lock_acq_rel.c
```

**Pull request merged**
