### PR TITLE
Add code to test double values with vector regs

### PR DESCRIPTION
**Pull request by janciesko**
New test.

### CODE REVIEW

**Comment by janciesko** [comment]
This still needs addition to the Makefile.am. We're currently not running this tests.

**Comment by cjhackillinois** [comment]
I'll work on getting the two new unit tests into the Makefile.

**Comment by janciesko** [comment]
New test pass on x68 and arm (incl. M1).

**Comment by janciesko** [comment]
This is ready for review

**Comment by cjhackillinois** [comment]
I gotta update so the code only prints if asserts fail
image

**Comment by janciesko** [comment]
LGTM. Please approve and I will merge.

**Review by cjhackillinois — APPROVED** [review]
This code servers as a basis for testing fast context switch of floating point values

**Review by olivier-snl — APPROVED** [review]

**Pull request merged**
